/* tslint:disable */
/* eslint-disable */
/**
 * Meals API
 * API for managing user accounts and authentication for the Meals service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginPost500Response
 */
export interface LoginPost500Response {
    /**
     * 
     * @type {string}
     * @memberof LoginPost500Response
     */
    error?: LoginPost500ResponseErrorEnum;
}


/**
 * @export
 */
export const LoginPost500ResponseErrorEnum = {
    AccessToken: 'Could not generate access token',
    RefreshToken: 'Could not generate refresh token'
} as const;
export type LoginPost500ResponseErrorEnum = typeof LoginPost500ResponseErrorEnum[keyof typeof LoginPost500ResponseErrorEnum];


/**
 * Check if a given object implements the LoginPost500Response interface.
 */
export function instanceOfLoginPost500Response(value: object): value is LoginPost500Response {
    return true;
}

export function LoginPost500ResponseFromJSON(json: any): LoginPost500Response {
    return LoginPost500ResponseFromJSONTyped(json, false);
}

export function LoginPost500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginPost500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

  export function LoginPost500ResponseToJSON(json: any): LoginPost500Response {
      return LoginPost500ResponseToJSONTyped(json, false);
  }

  export function LoginPost500ResponseToJSONTyped(value?: LoginPost500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

