/* tslint:disable */
/* eslint-disable */
/**
 * Meals API
 * API for managing user accounts and authentication for the Meals service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshPost401Response
 */
export interface RefreshPost401Response {
    /**
     * 
     * @type {string}
     * @memberof RefreshPost401Response
     */
    error?: RefreshPost401ResponseErrorEnum;
}


/**
 * @export
 */
export const RefreshPost401ResponseErrorEnum = {
    RefreshToken: 'Invalid refresh token',
    TokenClaims: 'Invalid token claims'
} as const;
export type RefreshPost401ResponseErrorEnum = typeof RefreshPost401ResponseErrorEnum[keyof typeof RefreshPost401ResponseErrorEnum];


/**
 * Check if a given object implements the RefreshPost401Response interface.
 */
export function instanceOfRefreshPost401Response(value: object): value is RefreshPost401Response {
    return true;
}

export function RefreshPost401ResponseFromJSON(json: any): RefreshPost401Response {
    return RefreshPost401ResponseFromJSONTyped(json, false);
}

export function RefreshPost401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshPost401Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

  export function RefreshPost401ResponseToJSON(json: any): RefreshPost401Response {
      return RefreshPost401ResponseToJSONTyped(json, false);
  }

  export function RefreshPost401ResponseToJSONTyped(value?: RefreshPost401Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

