/* tslint:disable */
/* eslint-disable */
/**
 * Meals API
 * API for managing user accounts and authentication for the Meals service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RefreshPost200Response
 */
export interface RefreshPost200Response {
	/**
	 *
	 * @type {string}
	 * @memberof RefreshPost200Response
	 */
	accessToken?: string;
}

/**
 * Check if a given object implements the RefreshPost200Response interface.
 */
export function instanceOfRefreshPost200Response(value: object): value is RefreshPost200Response {
	return true;
}

export function RefreshPost200ResponseFromJSON(json: any): RefreshPost200Response {
	return RefreshPost200ResponseFromJSONTyped(json, false);
}

export function RefreshPost200ResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RefreshPost200Response {
	if (json == null) {
		return json;
	}
	return {
		accessToken: json['access_token'] == null ? undefined : json['access_token']
	};
}

export function RefreshPost200ResponseToJSON(json: any): RefreshPost200Response {
	return RefreshPost200ResponseToJSONTyped(json, false);
}

export function RefreshPost200ResponseToJSONTyped(
	value?: RefreshPost200Response | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		access_token: value['accessToken']
	};
}
