/* tslint:disable */
/* eslint-disable */
/**
 * Meals API
 * API for managing user accounts and authentication for the Meals service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SignupPost500Response
 */
export interface SignupPost500Response {
	/**
	 *
	 * @type {string}
	 * @memberof SignupPost500Response
	 */
	error?: string;
}

/**
 * Check if a given object implements the SignupPost500Response interface.
 */
export function instanceOfSignupPost500Response(value: object): value is SignupPost500Response {
	return true;
}

export function SignupPost500ResponseFromJSON(json: any): SignupPost500Response {
	return SignupPost500ResponseFromJSONTyped(json, false);
}

export function SignupPost500ResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): SignupPost500Response {
	if (json == null) {
		return json;
	}
	return {
		error: json['error'] == null ? undefined : json['error']
	};
}

export function SignupPost500ResponseToJSON(json: any): SignupPost500Response {
	return SignupPost500ResponseToJSONTyped(json, false);
}

export function SignupPost500ResponseToJSONTyped(
	value?: SignupPost500Response | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		error: value['error']
	};
}
