/* tslint:disable */
/* eslint-disable */
/**
 * Meals API
 * API for managing user accounts and authentication for the Meals service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SignupPost400Response
 */
export interface SignupPost400Response {
	/**
	 *
	 * @type {string}
	 * @memberof SignupPost400Response
	 */
	error?: string;
}

/**
 * Check if a given object implements the SignupPost400Response interface.
 */
export function instanceOfSignupPost400Response(value: object): value is SignupPost400Response {
	return true;
}

export function SignupPost400ResponseFromJSON(json: any): SignupPost400Response {
	return SignupPost400ResponseFromJSONTyped(json, false);
}

export function SignupPost400ResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): SignupPost400Response {
	if (json == null) {
		return json;
	}
	return {
		error: json['error'] == null ? undefined : json['error']
	};
}

export function SignupPost400ResponseToJSON(json: any): SignupPost400Response {
	return SignupPost400ResponseToJSONTyped(json, false);
}

export function SignupPost400ResponseToJSONTyped(
	value?: SignupPost400Response | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		error: value['error']
	};
}
