info:
  contact: {}
paths:
  /ping:
    get:
      description: Returns a simple pong message
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Ping endpoint
      tags:
      - health
swagger: "2.0"
